---
allowed_outdate: 12h
mirrorlist_dir: docs/.vuepress/public/mirrorlist
mirrors_dir: mirrors.d
mirrors_table: docs/internal/mirrors.md
versions_arches:
  "8":
    - x86_64
    - aarch64
versions:
  - "8"
  - "8.6"
  - "9"
  - "9.0"
duplicated_versions:
  - "8"
  - "9"
vault_versions:
  - "8.4"
  - "8.5"
vault_mirror: https://vault.cdn.euro-linux.com/
arches:
  - x86_64
  - aarch64
# one of them should be in a mirror's config
required_protocols:
  - http
  - https
repos:
  - name: baseos
    path: $basearch/BaseOS/os/
  - name: appstream
    path: $basearch/AppStream/os/
  - name: powertools
    path: $basearch/PowerTools/os/
    versions:
      - "8"
  - name: crb
    path: $basearch/CRB/os/
    versions:
      - "9"
  - name: ha
    path: $basearch/HighAvailability/os/
    versions:
      - "8"
  - name: highavailability
    path: $basearch/HighAvailability/os/
    versions:
      - "9"
  - name: resilientstorage
    path: $basearch/ResilientStorage/os/
    arches:
      - x86_64
...
