---
allowed_outdate: 12h
mirrorlist_dir: docs/.vuepress/public/mirrorlist
mirrors_dir: mirrors.d
mirrors_table: docs/internal/mirrors.md
#versions_arches:
#  "8":
#    - x86_64
#    - aarch64
#  "9":
#    - x86_64
#    - aarch64
versions:
  - "8"
  - "9"
duplicated_versions:
  - 8.10
  - 9.4
vault_versions:
  - "6.10"
  - "7.7"
  - "7.8"
  - "7.9"
  - "8.4"
  - "8.5"
  - "8.6"
  - "8.7"
  - "8.8"
  - "8.9"
  - "9.0"
  - "9.1"
  - "9.2"
  - "9.3"
vault_mirror: https://vault.cdn.euro-linux.com/legacy/eurolinux/$releasever/
arches:
  - x86_64
  - aarch64
required_protocols:
  - http
  - https
repos:
  - name: baseos
    path: $basearch/BaseOS/os/
  - name: appstream
    path: $basearch/AppStream/os/
  - name: powertools
    path: $basearch/PowerTools/os/
    versions:
      - "8"
  - name: crb
    path: $basearch/CRB/os/
    versions:
      - "9"
  - name: ha
    path: $basearch/HighAvailability/os/
    arches:
      - x86_64
  - name: highavailability
    path: $basearch/HighAvailability/os/
    arches:
      - x86_64
  - name: resilientstorage
    path: $basearch/ResilientStorage/os/
    arches:
      - x86_64
  - name: extras
    path: $basearch/Extras/os/
    arches:
      - x86_64
    vault: true
  - name: updates
    path: $basearch/Updates/os/
    arches:
      - x86_64
    vault: true
...
